### ISSUE TITLE
Two images that cause crashes

### ISSUE THREAD

**Issue by Frozen1084** [WanzenBug/rqrr#9]
I encountered two crashes when testing different images using the example provided on the home page.

The first image that triggered the crash.
https://i.imgur.com/6fFOstK.jpeg
Crash message:
1thread 'main' panicked at 'Image index (81, 394) out of bounds (410, 392)', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\image-0.23.14\./src\buffer.rs:724:21

The second image that triggered the crash.
https://i.imgur.com/aF5kzW7.jpeg
Crash message:
1thread 'main' panicked at 'index out of bounds: the len is 41 but the index is 45', C:\Users\Administrator\.cargo\registry\src\github.com-1ecc6299db9ec823\rqrr-0.3.2\src\identify\grid.rs:349:17

**Comment by vi** [comment]
Similar panic:

```
thread '<unnamed>' panicked at 'index out of bounds: the len is 1778000 but the index is 18446744073709528139', /home/vi/.cargo/registry/src/github.com-1ecc6299db9ec823/rqrr-0.3.2/src/prepare.rs:74:9
```

**Comment by linkmauve** [comment]
Neither of these images crash current master or 0.10.1, and both are decoded correctly, you can close this issue.
